export const REGISTER_USERS_REQUEST = "REGISTER_USERS_REQUEST"
export const REGISTER_USERS_SUCCESS = "REGISTER_USERS_SUCCESS"
export const REGISTER_USERS_FAILURE = "REGISTER_USERS_FAILURE"

export const LOGIN_USERS_REQUEST = "LOGIN_USERS_REQUEST"
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS"
export const LOGIN_USERS_FAILURE = "LOGIN_USERS_FAILURE"

export const LOGOUT_USER = "LOGOUT_USER"

export const GITHUB_USERS_REQUEST = "GITHUB_USERS_REQUEST"
export const GITHUB_USERS_SUCCESS = "GITHUB_USERS_SUCCESS"
export const GITHUB_USERS_FAILURE = "GITHUB_USERS_FAILURE"

export const HANDLE_PAGE_CHANGE = "HANDLE_PAGE_CHANGE"

export const PROFILE_USERS_REQUEST = "PROFILE_USERS_REQUEST"
export const PROFILE_USERS_SUCCESS = "PROFILE_USERS_SUCCESS"
export const PROFILE_USERS_FAILURE = "PROFILE_USERS_FAILURE"