export const ADD_COUNTER = "ADD_COUNTER";
export const REDUCE_COUNTER = "REDUCE_COUNTER";
export const ADD_TODO = "ADD_TODO";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";


export const FETCH_GITHUB_REQUEST = "FETCH_GITHUB_REQUEST";
export const FETCH_GITHUB_SUCCESS = "FETCH_GITHUB_SUCCESS";
export const FETCH_GITHUB_FAILURE = "FETCH_GITHUB_FAILURE";
