const students =[{
    "id": 1,
    "first_name": "Candie",
    "last_name": "Curtoys",
    "email": "ccurtoys0@google.fr"
  }, {
    "id": 2,
    "first_name": "Maryann",
    "last_name": "Palombi",
    "email": "mpalombi1@ning.com"
  }, {
    "id": 3,
    "first_name": "Jaclin",
    "last_name": "Berkery",
    "email": "jberkery2@desdev.cn"
  }, {
    "id": 4,
    "first_name": "Morie",
    "last_name": "Kramer",
    "email": "mkramer3@bloomberg.com"
  }, {
    "id": 5,
    "first_name": "Cymbre",
    "last_name": "Ezele",
    "email": "cezele4@amazon.co.jp"
  }, {
    "id": 6,
    "first_name": "Benedicto",
    "last_name": "Behling",
    "email": "bbehling5@prweb.com"
  }, {
    "id": 7,
    "first_name": "Florian",
    "last_name": "Coryndon",
    "email": "fcoryndon6@senate.gov"
  }, {
    "id": 8,
    "first_name": "Toby",
    "last_name": "Hayle",
    "email": "thayle7@goodreads.com"
  }, {
    "id": 9,
    "first_name": "Donny",
    "last_name": "Ashbrook",
    "email": "dashbrook8@nyu.edu"
  }, {
    "id": 10,
    "first_name": "Aubert",
    "last_name": "Gori",
    "email": "agori9@ftc.gov"
  }, {
    "id": 11,
    "first_name": "Biddy",
    "last_name": "Squeers",
    "email": "bsqueersa@blinklist.com"
  }, {
    "id": 12,
    "first_name": "Helli",
    "last_name": "Tilsley",
    "email": "htilsleyb@bloomberg.com"
  }, {
    "id": 13,
    "first_name": "Aurlie",
    "last_name": "Tremble",
    "email": "atremblec@ow.ly"
  }, {
    "id": 14,
    "first_name": "Coralyn",
    "last_name": "Dealtry",
    "email": "cdealtryd@hhs.gov"
  }, {
    "id": 15,
    "first_name": "Elli",
    "last_name": "Laying",
    "email": "elayinge@paginegialle.it"
  }, {
    "id": 16,
    "first_name": "Keene",
    "last_name": "Dyka",
    "email": "kdykaf@topsy.com"
  }, {
    "id": 17,
    "first_name": "Cirillo",
    "last_name": "MacCrann",
    "email": "cmaccranng@de.vu"
  }, {
    "id": 18,
    "first_name": "Bellanca",
    "last_name": "McGunley",
    "email": "bmcgunleyh@ucoz.com"
  }, {
    "id": 19,
    "first_name": "Giorgi",
    "last_name": "McPhelimy",
    "email": "gmcphelimyi@msn.com"
  }, {
    "id": 20,
    "first_name": "Taite",
    "last_name": "Valentelli",
    "email": "tvalentellij@csmonitor.com"
  }, {
    "id": 21,
    "first_name": "Devin",
    "last_name": "Herkess",
    "email": "dherkessk@diigo.com"
  }, {
    "id": 22,
    "first_name": "Aura",
    "last_name": "Gosnay",
    "email": "agosnayl@ning.com"
  }, {
    "id": 23,
    "first_name": "Reinald",
    "last_name": "Alaway",
    "email": "ralawaym@nbcnews.com"
  }, {
    "id": 24,
    "first_name": "Daphene",
    "last_name": "Ferrone",
    "email": "dferronen@bloomberg.com"
  }, {
    "id": 25,
    "first_name": "Anastasie",
    "last_name": "Mayze",
    "email": "amayzeo@dmoz.org"
  }, {
    "id": 26,
    "first_name": "Reggie",
    "last_name": "Hampe",
    "email": "rhampep@issuu.com"
  }, {
    "id": 27,
    "first_name": "Chandra",
    "last_name": "Ruit",
    "email": "cruitq@wiley.com"
  }, {
    "id": 28,
    "first_name": "Bogart",
    "last_name": "Durdle",
    "email": "bdurdler@slate.com"
  }, {
    "id": 29,
    "first_name": "Yolane",
    "last_name": "Fennick",
    "email": "yfennicks@jiathis.com"
  }, {
    "id": 30,
    "first_name": "Glenine",
    "last_name": "Straughan",
    "email": "gstraughant@springer.com"
  }, {
    "id": 31,
    "first_name": "Allie",
    "last_name": "Dettmar",
    "email": "adettmaru@hibu.com"
  }, {
    "id": 32,
    "first_name": "Leone",
    "last_name": "Nassi",
    "email": "lnassiv@admin.ch"
  }, {
    "id": 33,
    "first_name": "Jessa",
    "last_name": "Parnby",
    "email": "jparnbyw@stanford.edu"
  }, {
    "id": 34,
    "first_name": "Jacquelin",
    "last_name": "Jiles",
    "email": "jjilesx@pinterest.com"
  }, {
    "id": 35,
    "first_name": "Peria",
    "last_name": "Kloser",
    "email": "pklosery@amazon.com"
  }, {
    "id": 36,
    "first_name": "George",
    "last_name": "Sworder",
    "email": "gsworderz@apache.org"
  }, {
    "id": 37,
    "first_name": "Trudey",
    "last_name": "Upstell",
    "email": "tupstell10@google.com.br"
  }, {
    "id": 38,
    "first_name": "Nissie",
    "last_name": "Walster",
    "email": "nwalster11@parallels.com"
  }, {
    "id": 39,
    "first_name": "Connor",
    "last_name": "Glasebrook",
    "email": "cglasebrook12@infoseek.co.jp"
  }, {
    "id": 40,
    "first_name": "Daphene",
    "last_name": "Kunneke",
    "email": "dkunneke13@tumblr.com"
  }, {
    "id": 41,
    "first_name": "Bryce",
    "last_name": "Dickey",
    "email": "bdickey14@amazon.com"
  }, {
    "id": 42,
    "first_name": "Melisent",
    "last_name": "Redley",
    "email": "mredley15@discuz.net"
  }, {
    "id": 43,
    "first_name": "Heddie",
    "last_name": "Patrickson",
    "email": "hpatrickson16@sciencedirect.com"
  }, {
    "id": 44,
    "first_name": "Verine",
    "last_name": "Maden",
    "email": "vmaden17@tuttocitta.it"
  }, {
    "id": 45,
    "first_name": "Mandy",
    "last_name": "Massey",
    "email": "mmassey18@google.co.uk"
  }, {
    "id": 46,
    "first_name": "Wolfie",
    "last_name": "Chadwell",
    "email": "wchadwell19@multiply.com"
  }, {
    "id": 47,
    "first_name": "Katerine",
    "last_name": "Marflitt",
    "email": "kmarflitt1a@bbb.org"
  }, {
    "id": 48,
    "first_name": "Auria",
    "last_name": "Knolles-Green",
    "email": "aknollesgreen1b@icio.us"
  }, {
    "id": 49,
    "first_name": "Kris",
    "last_name": "Wahncke",
    "email": "kwahncke1c@cnbc.com"
  }, {
    "id": 50,
    "first_name": "Riobard",
    "last_name": "Perigeaux",
    "email": "rperigeaux1d@eventbrite.com"
  }]

  module.exports = students;